using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;
using Microsoft.WindowsAPICodePack.Dialogs;
using Microsoft.WindowsAPICodePack.Shell.PropertySystem;

namespace Ruminoid.Trimmer.Shell.Models
{

    public sealed class LrcExporter
    {

        private static string AppendString =
            @"[Script Info]
; Generated by Ruminoid Trimmer
; https://ruminoid.vbox.moe/
Title: Karaoke Subtitle File
ScriptType: v4.00+

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,70,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
";

        public void Export(string path, ModeType type, Encoding encoding) => File.WriteAllText(path, Generate(LrcModel.Current, type), encoding);

        public string Generate(LrcModel model, ModeType type)
        {
            StringBuilder sb = new StringBuilder(AppendString);
            return sb.ToString();
        }

    }

}
